### ISSUE TITLE
Mandatory parameters without mandatory "true"

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#11]
Why do the following parameters not have mandatory "true";?
under babel
  version
  enable
under constants
  udp-port
under interfaces
  link-type
  metric-algorithm
under neighbor-objects
   txcost
   exp-mcast-hello-seqno
   exp-ucast-hello-seqno

I don't know enough about YANG to know how to express conditional mandatory for hmac and dtls lists. That is, 
If hmac list is implemented, then all the parameters are mandatory. 
If dtls list is implemented, then interfaces and apply-all are mandatory.
If hmac list is implemented, then hmac-key is implemented, and all but test are mandatory.
If dtls list is implemented, then dtls-certs is implemented and all but test are mandatory.
If test is implemented, then the test-string (input) and resulting-hash (output) are mandatory.

So if "?" next to all these is ok, then I'm fine with that. I just thought I'd mention it.

**Comment by mjethanandani** [comment]
A "?" next to attribute means it is optional.

Where in the IM does it indicate that version field is mandatory? (I know that it should be mandatory), but it would help if IM made it explicit. Maybe by putting <1> after the attribute name??

Regardless, I will make them mandatory either by putting a 'mandatory true' statement or by putting a default value.

**Comment by bhstark2** [comment]
Info-model uses the convention that anything with square brackets around it is optional. If it doesn't have square brackets, it's mandatory. This convention is described in the first paragraph under 1.2 Notation. I chose conventions used in [rfc8193 ](https://tools.ietf.org/html/rfc8193) because Juergen Schoenwaelder was a co-author of that. So I figured these conventions would be acceptable.

**Comment by mjethanandani** [comment]
Yes, remember you talking about it. Thanks.

**Comment by mjethanandani** [comment]
Not quite ready to close it, till I have update the model.

**Comment by mjethanandani** [comment]
How do you make a ro parameter to be "mandatory true"? Yes, the implementation should provide it, but there is no way to enforce it. Who, when, and where will a ro parameter be validated for mandatory true status?

Suggest all ro parameters not be made mandatory.

**Comment by mjethanandani** [comment]
To this question.
> I don't know enough about YANG to know how to express conditional mandatory for hmac and dtls lists. That is,
> If hmac list is implemented, then all the parameters are mandatory.
> If dtls list is implemented, then interfaces and apply-all are mandatory.
> If hmac list is implemented, then hmac-key is implemented, and all but test are mandatory.
> If dtls list is implemented, then dtls-certs is implemented and all but test are mandatory.
> If test is implemented, then the test-string (input) and resulting-hash (output) are mandatory.

There is no way to express conditional mandatory case on all parameters within a given parent. One would have to mark each node in the parent that needs to be mandatory as 'mandatory true". 

In the above example, if a hmac entry exists, and we want all parameters within it to be mandatory, we will have to make them all 'mandatory true'. For dtls, we will have to make interfaces and apply-all as mandatory etc. 

For actions, input statement itself is not mandatory, but a substatement like a leaf argument can be made mandatory. So for 'action test' I can make test-string and resulting-has as mandatory.

**Comment by bhstark2** [comment]
I'm in over my head on how to express conditional mandatory. So I won't worry about that.
But I've been looking through various YANG models and have found many mandatory ro leafs. For example, see RFC8194 (which Juergen co-authored) module: ietf-lmap-control. The capabilities container in that is specifically about reporting capabilities (not unlike all these Babel ro parameters), and several of the ro leafs are mandatory "true". 
I don't exactly understand your question about who would validate it or how they would enforce it, because I realize there's special stuff in YANG for validation/enforcement that I don't fully comprehend. So I can't answer that. All I know is it's been done in other YANG models.

**Comment by mjethanandani** [comment]
Fair enough. When we are in Prague, and we are down a couple of beers, ask me the question. Maybe my explanation might more sense than it is making now :-).

**Comment by mjethanandani** [comment]
For now, all leafs that are rw, I have added 'mandatory true' capability by giving some of them a default value, and those that I was not sure of a default value, added mandatory true statement. That change has been pushed into the merge request.

We can revisit what to do for the version attribute, the only attribute which is ro, and for which I do not have a resolution currently.

**Comment by bhstark2** [comment]
Comprehension is slowly dawning, as I read more of RFC7950. So a NETCONF server is required to faithfully support an advertised module in its entirety. Where it doesn't, it has to explicitly identify this through "deviation" statements. So the info-model square brackets' concept of "mandatory" isn't relevant within a YANG module definition. Such mandatoriness would need to be ensured external to the YANG module (e.g., through a compliance test that makes sure there are no "deviation" statements for mandatory info-model parameters). The YANG concept of "mandatory" is about whether the leaf(-list) has to have a value (when being written or created). If mandatory, there MUST NOT be a default. Do I understand correctly?
Which would explain why YANG mandatory "true" isn't particularly meaningful for a ro leaf. It is what it is.

If I'm getting this right, then...
After reviewing all the mandatory "true" leafs, I think the one on router-id may not be needed but won't hurt anything either.
The only one I wonder about is the dtls private-key. If it's ok for the value provided to a mandatory leaf to be the empty string, then this is ok. But I think it would also be ok for this not to be mandatory. Certs in this list that are for other devices will have an empty private-key value.

min-elements: I don't think any of the min-elements "1" are right. According to the "<0..*>" next to these lists in the info-model, these can all have zero instances.

**Comment by mjethanandani** [comment]
> Comprehension is slowly dawning, as I read more of RFC7950. So a NETCONF server is required to faithfully support an advertised module in its entirety. Where it doesn't, it has to explicitly identify this through "deviation" statements. So the info-model square brackets' concept of "mandatory" isn't relevant within a YANG module definition. Such mandatoriness would need to be ensured external to the YANG module (e.g., through a compliance test that makes sure there are no "deviation" statements for mandatory info-model parameters). The YANG concept of "mandatory" is about whether the leaf(-list) has to have a value (when being written or created). If mandatory, there MUST NOT be a default. Do I understand correctly?

That is correct. However, what it also saying is that you should not have both a mandatory keyword and a default keyword under the leaf(-list) at the same time.

**Comment by mjethanandani** [comment]
> min-elements: I don't think any of the min-elements "1" are right. According to the "<0..*>" next to these lists in the info-model, these can all have zero instances.

I added min-elements to (leaf)-list like interfaces because there are no square brackets around them, which according to convention means the list is mandatory. But as you point out that list can be 0, because it is <0..*>. Don't you think that is contradictory? Either the list is mandatory (and it has at least one element) or it is not mandatory (has a square bracket around it). What gives?

**Comment by mjethanandani** [comment]
> Which would explain why YANG mandatory "true" isn't particularly meaningful for a ro leaf. It is what it is.

That is correct. When the client sends a request to configure babel, it does not/cannot send a request to the server to modify a ro leaf-(list). The server will either ignore it or return an error. A ro leaf-(list) is set by the server itself for the client to read. So making it mandatory does not make sense. What is client supposed to do if the value is not set? Complain??

**Comment by mjethanandani** [comment]
> After reviewing all the mandatory "true" leafs, I think the one on router-id may not be needed but won't hurt anything either.

Ok. I will keep it then.

> The only one I wonder about is the dtls private-key. If it's ok for the value provided to a mandatory leaf to be the empty string, then this is ok. But I think it would also be ok for this not to be mandatory. Certs in this list that are for other devices will have an empty private-key value.

If the leaf is mandatory, it has to have a value. An empty string is not a value. Should I make the dtls private-key and the list of certs NOT mandatory?

**Comment by bhstark2** [comment]
I've determined info-model square bracket effectively means (in the context of YANG) that a server conforming to babel-information-model will not include deviation statements with deviate not-supported sub-statements for leafs and leaf-lists representing info-model elements without square brackets. But the server can still be considered conformant if it has deviation statements with deviate not-supported sub-statements for data nodes representing info-model elements with square brackets. Where leafs and leaf-lists of info-model elements without square brackets are inside lists from elements with square brackets, it's ok for there to be a deviation where the list in its entirety is not-supported. Might it be useful to mention this in the introductory section on the information model? If appropriate, this could be worded using normative language (e.g., "A server conforming to babel-information-model MUST NOT ...").
I see no other way to express the square brackets in the YANG DM.

**Comment by bhstark2** [comment]
So if we agree that square brackets don't get represented in the YANG DM directly, I think YANG "mandatory", "default", and "min-elements" are done as (suggested changes in bold): 
There are no writable (rw) lists or leaf-lists that require an instance to exist (<1..*>). **No list or leaf-list should have a min-elements statement.** (suggested change)
ro leafs and leaf-lists are fine without mandatory or default, but the couple of cases where there is a mandatory statement (metric and router-id) are ok.
rw leafs and leaf-lists inside ro lists (list instance cannot be created by client) will have values initially set by server. It's ok if client doesn't write these, so none should be mandatory "true" (and none are, so no change needed). Defaults that are listed are ok.
rw Boolean leafs inside rw lists (hmac, hmac-keys, dtls, certs) either need to mandatory or have a default. They're all mandatory now, so that's ok.

rw non-Boolean leafs and leaf-lists inside rw lists need to be considered individually:
- hmac algorithm: **I think this needs to be mandatory "true"** -- we can't have a client creating a hmac instance without this, and there's no default (suggested change)
- hmac interfaces: This can be empty, so **I think it needs no min-elements, no mandatory, no default** (suggested change)
- dtls interfaces: like hmac interfaces, **no min-elements, no mandatory, no default**. (suggested change
- certs name: (new parameter) **I think this should be like hmac-keys name and mandatory "true"** (suggested change)
- certs private-key: can be empty, **so no default and no mandatory "true"** (suggested change)
- all others are ok

**Comment by mjethanandani** [comment]
I do not know if the confusion around how YANG implements mandatory requirement stems from something I said, or it has something you read in RFC 7950. If it is latter, let me know what you read in the draft that led you this line of thinking.

Broadly, in YANG a mandatory statement (or min-element statement under a list or leaf-list), means that the client trying to configure the server MUST provide a value for that attribute. The model can also satisfy the mandatory requirement by suggesting a value by using the default statement.


> Where leafs and leaf-lists of info-model elements without square brackets are inside lists from elements with square brackets, it's ok for there to be a deviation where the list in its entirety is not-supported.

The scope of a mandatory element is to the closest parent within which the mandatory element exists. So if a non-mandatory list, i.e. 'list dtls', contains a mandatory element, i.e. 'leaf apply-all', the enforcement of mandatory on 'apply-all' leaf will be applied only if the 'list dtls' exists. If 'list dtls' has no elements defined, then there is no question of trying to enforce mandatory on 'apply-all'. It does not even exist.

My question was specifically around this line in the babel-information-obj:

babel-interfaces-obj ro babel-interfaces<0..*>;

There are no square brackets around babel-interfaces, which means it is mandatory for this list to have at least one element. But you say that the list can be 0. This can mean two things. Either there are no interfaces that are enabled for Babel (which makes no sense to me), or it means that interface configuration is global and applies to all interfaces. I think it means the latter. If that is the case, I think it would be better to have a separate leaf in babel-information-obj similar to "apply-all" later in the model. And it would be useful to say that in the information model, under the description of babel-interfaces. 

The babel-interfaces attribute should be for specifying which interfaces are receiving/sending babel packets.

**Comment by bhstark2** [comment]
The square brackets do not mean mandatory in the YANG sense. They need to completely be ignored when defining this YANG DM. It may be useful to say something about them in the info-model section of the YANG draft. An implementation advertising the Babel YANG DM will not be compliant with info-model if it has **deviation statements** that indicate not-supported for any parameters or objects that don't have square brackets.
Specifically wrt interfaces, some Babel implementations are just keeping track of interfaces where Babel is running, and are running Babel on all LAN interfaces with physical and MAC layers running. They won't support "enable" on an interface (it's allowed to deviate by not supporting interface-enable). For these, the global Babel enable is all there is for turning Babel on or off (on all "up" LAN interfaces). So global configuration (applies to all interfaces) is already supported by the top level Babel enable, if interface-enable is not supported. If interface-enable is supported, then Babel enable can only enable interface-enabled interfaces.
It's possible for no LAN interface to have physical and MAC running (all Wi-Fi radios disabled and no Ethernet cable plugged in) at a particular point in time, even though Babel is enabled. An interface must at least have a self-assigned link-local IPv6 address, and this doesn't happen if media are off or disconnected. In this case, there are no interface instances that Babel can or does operate over. This is why it's possible for there to be no interface instances.
Of course, if this happens, remote management will be fairly impossible. Console management may still be possible.
