### ISSUE TITLE
hmac, dtls, certs unique keys

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#13]
We do need to figure out how to get good unique keys for hmac, dtls, and certs lists, because hmac algorithm and certs type won't work (and dtls name isn't fully defined, and whatever gets done should be done consistently). I understand that you'd prefer for the info-model to explicitly identify a unique key for these, and I've mentioned that for TR-181 I don't have this unique key problem because every instance automatically gets an instance number and an Alias that are used as a unique key in the absence of a "real" unique key. 

My preference would be if you did like what you have (albeit incomplete) under dtls, with the "name" leaf. Or like people do with sql tables where they create a special table key parameter that gets auto-assigned a number. Is there no precedent for this sort of thing in YANG?

**Comment by bhstark2** [comment]
I think it would make sense to add a "name" parameter / leaf to certs, in the info model. That would take care of it. I'll note that under info-model issues.
For dtls and hmac I want to wait for any changes that might come from resolving question of whether instances need to be additive for interfaces.

**Comment by mjethanandani** [comment]
Ok. Will add the 'name' parameter as a leaf in the list of certs, and make that the key.

**Comment by mjethanandani** [comment]
Added 'name' to both hmac and dtls list.
