### ISSUE TITLE
Link Types

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#5]
Can we delete these from the link-type identity? They won't be among those created in the new IANA registry. Additional link types will only be defined when the type has an impact on metric calculation (needs its own algorithm).
  identity moca
  identity g-hn-over-coax
  identity g-hn-over-powerline
  identity home-plug
  identity ieee-802-15

**Comment by mjethanandani** [comment]
Understood. How does one for example, know that for moca which other identity should be used to get the same metric value?

**Comment by bhstark2** [comment]
We might want to have a discussion in Prague around the values in the proposed registry for Babel link types. I think "Ethernet" and some of the references I list are confusing. My own understanding of this has evolved since my first stab at that table. 
When I carefully read what Juliusz says, he explains that so far as he's been able to determine there are just 3 types of interfaces the Babel algorithms need to deal with: wireless (very unpredictable and unstable), wired (tends to be stable), and tunneled (which apparently has some special behaviors). And then there's "default" (can't figure this out, so give it a "default" treatment initially -- which is either wired or wireless; based on the link's behavior over time, that treatment (and assigned link type) can dynamically change). Until he finds something that doesn't do well when put into one of these categories (i.e., requires a different algorithm), he doesn't want to have additional link types that are just abstractions of one of these basic 4 link types. He would characterize MOCA as exhibiting "wired" behavior.
I had initially thought we would need more link types. But Juliusz doesn't want them until they prove themselves to be different. However, I don't think Juliusz has really experimented with no-new-wires PHYs. So he could be wrong.

**Comment by mjethanandani** [comment]
Ok. Let us keep this issue open till we have had a chance to get some clarity around it.

**Comment by mjethanandani** [comment]
Link type is now link properties, and they have redefined in the information model.
