### ISSUE TITLE
routes prefix+prefix-length

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#6]
Would it make sense to just combine these 2 parameters and use the YANG ip-prefix type? That's what I did in my TR-181 DM.

**Comment by mjethanandani** [comment]
I do not think you can combine them.  The prefix, or network, is the network portion of the IP address, and the prefix length, or subnet mask, is the number that follows the slash after the IP address. For example if you have the route 1.2.3.0/24, the prefix/network is 1.2.3.0, and the prefix length/subnet mask is /24 or 255.255.255.0.

**Comment by bhstark2** [comment]
The ip-prefix type (from [RFC6991](https://tools.ietf.org/html/rfc6991)) can be of ipv4-prefix or ipv6-prefix type and includes an IP address, a "/" and a prefix length in its definition.

**Comment by mjethanandani** [comment]
Ahh. That is correct. The description was not clear, but the regex pattern is clear that it includes both the IP address and the prefix-length. Thanks for pointing out.

**Comment by mjethanandani** [comment]
Change pushed into merge request.
