### ISSUE TITLE
binary data type

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#7]
I don't see a definition of a binary data type in RFC 6991 (is that the right place for me to check these?) and it's not defined in here as a special data type. Is that a problem?
In TR-181 I modeled all these binary parameters as "hexBinary" (analogous to the YANG hex-string). Would that make sense here? In discussing this "binary" info model type, it was noted that data models would need to identify how to encode these parameters in their context.

**Comment by mjethanandani** [comment]
You will find it in RFC 7950. https://tools.ietf.org/html/rfc7950#page-157.

A couple of sections down it tells you that base64 encoding is used to encode binary data.
