### ISSUE TITLE
babel version parameter

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#8]
defined as "This is the version of the babel protocol implemented."

The info-model parameter implementation-version is not the version of the Babel protocol (which the Babel WG participants said they didn't think as useful information). It's the version (and name) of the software. There are currently 6 different implementations which support optional features to different extents -- so it's important to know which implementation you're dealing with. As they revise their implementations with bug fixes and additional features, it's important to know which version of an implementation you're dealing with.
External to Babel, it's often possible to load a different implementation, if you don't like the one that's currently in your router. Or upgrade/update the implementation if there's a newer version. But first you need to know what's there.

**Comment by mjethanandani** [comment]
Ok. WIll update the description.

**Comment by mjethanandani** [comment]
Change pushed into merge request.
