### ISSUE TITLE
interfaces link-type

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#9]
Is it possible to constrain this to just being one of those in the babel container link-type list?
The description doesn't seem quite right.

**Comment by mjethanandani** [comment]
You mean the 'leaf link-type' in the 'list interfaces'? If so, yes, they are constrained by the fact that they are an' identityref' of base type 'link-type', which as would have seen, have been defined as identities in the beginning of the model.

**Comment by bhstark2** [comment]
But the current description here doesn't constrain interfaces link-type to only being one of the values listed in babel container link-type. If babel container link-type only has 2 values listed as being supported, then interfaces link-type has to be one of those 2 values, and can't be any of the other values from the identityref. You have this sort of constraint specified in other parameters of this ilk: leaf metric-algorithm, hmac leaf algorithm, dtls-cert-types.

**Comment by mjethanandani** [comment]
The babel container 'leaf-list link-type' is defined as:

```
     leaf-list link-type {
	type identityref {
	  base "link-type";
	}
	description
	  "Link types supported by this implementation of Babel.";
	reference
	  "RFC ZZZZ, Babel Information Model, Section 3.1.";
      }

```

and the interface 'leaf link-type' is defined as:


```
	leaf link-type {
          type identityref {
            base link-type;
          }
	  default "ethernet";
          description
            "Indicates the type of link. Set of values of supported
             link types where the following enumeration values MUST
             be supported when applicable: 'ethernet', 'wireless',
             'tunnel', and 'other'. Additional values MAY be
             supported.";
          reference
            "RFC ZZZZ, Babel Information Model, Section 3.3.";
        }

```

both are of 'base' type 'link-type'. That means both have to be of type 'identity link-type', i.e. either 'ethernet' or 'other' or 'tunnel' or ...

Does that help, or did I confuse you even more :-)

**Comment by mjethanandani** [comment]
Ok. I think I finally get what you were trying to say. Once the leaf-list in the babel container is populated with say 2 link-types, only those 2 link-types can be configured in the interface link-type.

Let me see how I can constrain it.

**Comment by mjethanandani** [comment]
link-type is no longer a parameter in the model.
